services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'Guiatu2'
    volumes:
      - ./database_pi.sql:/docker-entrypoint-initdb.d/database_pi.sql
    ports:
      - "3307:3306"

  pythonapp:
    build: ./app
    depends_on:
      - mysql
    ports:
      - "4000:5000"
    volumes:
      - ./app:/app
    environment:
      FLASK_ENV: development